name: commerce
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  fl_chart: ^1.1.1           # remplacement de charts_flutter par fl_chart
  file_picker: ^10.3.7
  flutter_facebook_auth: ^7.1.2
  flutter_secure_storage: ^9.2.4
  http: ^1.6.0
  dio: ^5.1.2
  csv: ^5.0.0
  iconsax: ^0.0.8
  shared_preferences: ^2.5.3
  image_picker: ^1.2.1
  hive: ^2.2.3
  intl: ^0.20.2
  hive_generator: ^2.0.0
  build_runner: ^2.4.0
  flutter_animate: ^4.5.2
  font_awesome_flutter: ^10.12.0
  flutter_form_builder: ^10.2.0
  form_builder_validators: ^11.2.0
  pull_to_refresh: ^2.0.0
  uuid: ^4.5.2
  syncfusion_flutter_charts: ^31.2.16
  url_launcher: ^6.3.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true